import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const LETTERS=['A','B','C','D','E'];
const EXAM_MINUTES=120;
const TOTAL=100;

const BANK = [
// MEDICINE / INTEGRATED BASIC SCIENCES
{id:'M01',subject:'Medicine',q:'A 64-year-old man with severe COPD has chronic hypercapnia. Which renal adaptation most directly explains his near-normal arterial pH?',o:['Reduced proximal bicarbonate reabsorption','Increased ammonium excretion and new bicarbonate generation','Reduced hydrogen ion secretion in the collecting duct','Increased chloride retention without bicarbonate change','Reduced glutamine metabolism in the proximal tubule'],a:1,e:'Chronic respiratory acidosis is compensated by increased renal H+ excretion, especially as NH4+, with generation/retention of bicarbonate.'},
{id:'M02',subject:'Medicine',q:'A patient with cirrhosis develops tense ascites and a low serum sodium. Which mechanism is most responsible for the impaired free-water excretion?',o:['Primary renal sodium wasting','Reduced ADH release','Reduced effective arterial blood volume causing non-osmotic ADH release','Increased atrial natriuretic peptide secretion','Suppression of the renin-angiotensin system'],a:2,e:'Reduced effective arterial blood volume activates RAAS and sympathetic tone and produces non-osmotic ADH secretion, impairing free-water excretion.'},
{id:'M03',subject:'Medicine',q:'A patient taking warfarin develops an unexpectedly prolonged PT after starting trimethoprim-sulfamethoxazole. The most important pharmacologic explanation is:',o:['Induction of CYP2C9','Inhibition of warfarin metabolism with reduced vitamin K–producing flora','Increased renal clearance of warfarin','Direct activation of protein C','Reduced intestinal absorption of warfarin'],a:1,e:'TMP-SMX can inhibit CYP-mediated warfarin metabolism and reduce vitamin K production, increasing anticoagulant effect.'},
{id:'M04',subject:'Medicine',q:'A 23-year-old woman has episodic palpitations, sweating and headache. Plasma metanephrines are elevated. Before alpha blockade, beta blockade is given. What is the major danger?',o:['Severe bradycardia','Unopposed alpha-adrenergic vasoconstriction causing hypertensive crisis','Acute hypoglycemia','Pulmonary edema from beta-2 stimulation','Adrenal hemorrhage'],a:1,e:'In pheochromocytoma, beta blockade before adequate alpha blockade can leave alpha-mediated vasoconstriction unopposed and precipitate severe hypertension.'},
{id:'M05',subject:'Medicine',q:'Which acid-base pattern is most characteristic of salicylate toxicity in an adult early in the course?',o:['Pure metabolic alkalosis','Pure respiratory acidosis','Respiratory alkalosis with an increased anion-gap metabolic acidosis','Normal anion-gap metabolic acidosis only','Respiratory acidosis with metabolic alkalosis'],a:2,e:'Salicylates stimulate the respiratory center causing respiratory alkalosis and later produce an anion-gap metabolic acidosis.'},
{id:'M06',subject:'Medicine',q:'A patient with nephrotic syndrome develops renal vein thrombosis. Loss of which urinary protein most contributes to the thrombotic tendency?',o:['Albumin','Transferrin','Antithrombin III','Ceruloplasmin','Haptoglobin'],a:2,e:'Urinary loss of antithrombin III, along with increased hepatic procoagulant synthesis and platelet activation, contributes to thrombosis.'},
{id:'M07',subject:'Medicine',q:'A patient with SIADH has serum sodium 116 mmol/L, low serum osmolality and inappropriately concentrated urine. Which finding best supports SIADH over hypovolemic hyponatremia?',o:['Urine sodium <10 mmol/L','Elevated BUN/creatinine ratio','Urine sodium >30 mmol/L with clinical euvolemia','Orthostatic hypotension','Marked peripheral edema'],a:2,e:'SIADH typically produces euvolemic hyponatremia with inappropriately concentrated urine and urine sodium that is not suppressed.'},
{id:'M08',subject:'Medicine',q:'A 58-year-old with exertional chest pain has a harsh systolic murmur at the right upper sternal border radiating to the carotids. Which pulse finding is most expected?',o:['Bounding pulse with wide pulse pressure','Pulsus alternans','Pulsus paradoxus','Pulsus parvus et tardus','Bisferiens pulse'],a:3,e:'Severe aortic stenosis classically produces a low-amplitude, delayed carotid upstroke: pulsus parvus et tardus.'},
{id:'M09',subject:'Medicine',q:'A patient with hypertrophic obstructive cardiomyopathy becomes more symptomatic after dehydration. Which maneuver most increases the dynamic outflow obstruction?',o:['Squatting','Passive leg raising','Handgrip','Standing suddenly','Phenylephrine administration'],a:3,e:'Reduced preload with standing decreases LV cavity size and worsens systolic anterior motion of the mitral valve and LV outflow obstruction.'},
{id:'M10',subject:'Medicine',q:'A patient with acute pulmonary edema has severe hypertension and a new S3. Which immediate hemodynamic change most rapidly reduces LV preload and afterload?',o:['Low-dose dopamine','High-dose IV nitrate','Digoxin','Phenylephrine','Fluid bolus'],a:1,e:'High-dose nitrates produce venodilation and arterial dilation, rapidly reducing preload and afterload in hypertensive acute pulmonary edema.'},
{id:'M11',subject:'Medicine',q:'Which ECG feature most strongly favors hyperkalemia rather than acute myocardial infarction in a patient with weakness?',o:['Localized ST elevation','Peaked, narrow-based T waves diffusely','Pathologic Q waves','Reciprocal ST depression in a coronary distribution','New left bundle branch block'],a:1,e:'Diffuse tall peaked T waves are an early classic ECG manifestation of hyperkalemia; later changes include PR prolongation and QRS widening.'},
{id:'M12',subject:'Medicine',q:'A patient has fever, new murmur, splinter hemorrhages and positive blood cultures. Which cardiac valve is most commonly involved in native-valve infective endocarditis?',o:['Pulmonary','Tricuspid','Aortic','Mitral','Eustachian'],a:3,e:'The mitral valve is the most commonly affected native valve in infective endocarditis, followed by the aortic valve.'},
{id:'M13',subject:'Medicine',q:'A young adult develops hemoptysis, rapidly progressive renal failure and pulmonary-renal syndrome. Which antibody is most directly associated with anti-GBM disease?',o:['Anti-dsDNA','Anti-GBM antibody','Anti-centromere','Anti-mitochondrial','Anti-CCP'],a:1,e:'Anti-GBM antibodies target the alpha-3 chain of type IV collagen in glomerular and alveolar basement membranes.'},
{id:'M14',subject:'Medicine',q:'A patient with nephritic syndrome has low complement and a recent streptococcal pharyngitis. Which renal lesion is most likely?',o:['Minimal change disease','Membranous nephropathy','Diffuse endocapillary proliferative glomerulonephritis','Focal segmental glomerulosclerosis','Alport syndrome'],a:2,e:'Post-streptococcal glomerulonephritis causes diffuse endocapillary proliferation with granular immune deposits and subepithelial humps.'},
{id:'M15',subject:'Medicine',q:'A 30-year-old has recurrent renal stones, hypercalcemia, low phosphate and elevated PTH. Which additional finding is most likely?',o:['Low urinary calcium in all cases','Metabolic acidosis from distal RTA','Increased bone turnover','Suppressed alkaline phosphatase','Increased calcitonin'],a:2,e:'Primary hyperparathyroidism increases bone turnover, renal calcium excretion and activation of vitamin D, while reducing phosphate reabsorption.'},
{id:'M16',subject:'Medicine',q:'A patient with severe diarrhea has a normal-anion-gap metabolic acidosis. Which renal response should occur?',o:['Reduced ammonium excretion','Increased bicarbonate generation and ammonium excretion','Reduced distal hydrogen secretion','Increased urinary bicarbonate loss','Suppressed glutamine metabolism'],a:1,e:'Extrarenal bicarbonate loss triggers increased renal acid excretion, including ammonium, and generation/retention of bicarbonate.'},
{id:'M17',subject:'Medicine',q:'A patient with cirrhosis develops hepatic encephalopathy. Which neurotransmitter-related change is most implicated in the clinical syndrome?',o:['Reduced GABAergic tone','Increased GABAergic inhibitory signaling and neurosteroid activity','Increased dopamine synthesis only','Reduced astrocyte glutamine','Increased acetylcholine release'],a:1,e:'Ammonia and other factors promote astrocyte dysfunction and enhanced inhibitory neurosteroid/GABAergic signaling in hepatic encephalopathy.'},
{id:'M18',subject:'Medicine',q:'A patient with painless jaundice has a palpable, non-tender gallbladder. This finding is classically associated with obstruction from:',o:['A gallstone impacted in the cystic duct','A pancreatic head malignancy','Acute viral hepatitis','Hemolysis','Primary biliary cholangitis'],a:1,e:'A painless enlarged gallbladder with obstructive jaundice (Courvoisier sign) suggests malignant distal biliary obstruction, classically pancreatic head cancer.'},
{id:'M19',subject:'Medicine',q:'A patient with chronic diarrhea, iron deficiency and dermatitis herpetiformis has a biopsy showing villous atrophy. Which antibody is most useful for screening?',o:['Anti-mitochondrial IgM','IgA anti-tissue transglutaminase','Anti-dsDNA','Anti-GBM','Anti-smooth muscle only'],a:1,e:'IgA anti-tissue transglutaminase is a preferred screening test for celiac disease, with total IgA considered because selective IgA deficiency can occur.'},
{id:'M20',subject:'Medicine',q:'A patient with ulcerative colitis develops pruritus and cholestatic liver enzymes. MRCP shows multifocal strictures and beading. Which diagnosis is most likely?',o:['Primary biliary cholangitis','Primary sclerosing cholangitis','Autoimmune hepatitis','Wilson disease','Budd-Chiari syndrome'],a:1,e:'PSC causes multifocal intrahepatic and extrahepatic biliary strictures and is strongly associated with inflammatory bowel disease.'},
{id:'M21',subject:'Medicine',q:'A patient with recurrent infections, eczema and thrombocytopenia with small platelets is suspected of having an X-linked immunodeficiency. The defective protein is:',o:['Bruton tyrosine kinase','Wiskott-Aldrich syndrome protein','NADPH oxidase','CD40 ligand','ADA'],a:1,e:'Wiskott-Aldrich syndrome causes eczema, recurrent infections and thrombocytopenia with characteristically small platelets.'},
{id:'M22',subject:'Medicine',q:'A man develops flushing, diarrhea, bronchospasm and right-sided valvular fibrosis from a neuroendocrine tumor. Which substance most directly causes the valvular lesion?',o:['Histamine','Serotonin','Dopamine','Bradykinin','Leukotriene B4'],a:1,e:'Carcinoid syndrome is associated with serotonin excess; serotonin and other mediators contribute to right-sided endocardial/valvular fibrosis.'},
{id:'M23',subject:'Medicine',q:'A patient has proximal muscle weakness, heliotrope rash and Gottron papules. Which laboratory abnormality is most likely?',o:['Low creatine kinase','Elevated creatine kinase','Low aldolase only','Markedly elevated troponin I with normal CK','Isolated alkaline phosphatase elevation'],a:1,e:'Dermatomyositis causes inflammatory myopathy with elevated muscle enzymes, commonly CK and aldolase.'},
{id:'M24',subject:'Medicine',q:'A patient with rheumatoid arthritis develops splenomegaly and neutropenia. This triad is known as:',o:['Still syndrome','Felty syndrome','Sjögren syndrome','Caplan syndrome','Goodpasture syndrome'],a:1,e:'Felty syndrome classically consists of seropositive rheumatoid arthritis, splenomegaly and neutropenia.'},
{id:'M25',subject:'Medicine',q:'A patient has episodic weakness, hypertension and hypokalemia. Renin is suppressed and aldosterone is elevated. Which mechanism is most likely?',o:['Renal artery stenosis','Primary hyperaldosteronism','SIADH','Addison disease','Pheochromocytoma alone'],a:1,e:'Primary hyperaldosteronism produces autonomous aldosterone secretion with suppressed renin, hypertension and potassium wasting.'},
{id:'M26',subject:'Medicine',q:'A patient with suspected Cushing syndrome has an elevated overnight dexamethasone suppression test and ACTH is high. Which next test best distinguishes pituitary from ectopic ACTH production?',o:['Serum TSH','High-dose dexamethasone suppression test or inferior petrosal sinus sampling depending on pathway','Urine sodium','Plasma renin','Serum aldosterone'],a:1,e:'ACTH-dependent Cushing syndrome requires localization; high-dose dexamethasone may suppress pituitary ACTH, while inferior petrosal sinus sampling is a highly discriminating test.'},
{id:'M27',subject:'Medicine',q:'A patient with hyperthyroidism develops fever, delirium, tachycardia and heart failure after surgery. Which treatment should be given early?',o:['Levothyroxine','Propranolol plus thionamide and iodine after thionamide','Radioactive iodine immediately','Calcium gluconate alone','Desmopressin'],a:1,e:'Thyroid storm requires rapid adrenergic control and inhibition of hormone synthesis; iodine is given after thionamide to avoid providing substrate for new hormone synthesis.'},
{id:'M28',subject:'Medicine',q:'A patient with hypothyroidism has hyponatremia, hypothermia, bradycardia and altered consciousness. Which diagnosis is most likely?',o:['Thyroid storm','Myxedema coma','Adrenal crisis only','Neuroleptic malignant syndrome','Serotonin syndrome'],a:1,e:'Severe decompensated hypothyroidism can cause myxedema coma, with hypothermia, bradycardia, hyponatremia and altered mental status.'},
{id:'M29',subject:'Medicine',q:'A patient with chronic kidney disease has normocytic anemia. Which mechanism contributes most directly?',o:['Excess erythropoietin production','Reduced erythropoietin production by diseased kidneys','Folate overproduction','Hemolysis in every case','Increased intestinal iron absorption'],a:1,e:'Reduced renal erythropoietin production is the major cause of anemia of advanced chronic kidney disease.'},
{id:'M30',subject:'Medicine',q:'A patient develops thrombocytopenia, microangiopathic hemolytic anemia, fever and neurologic abnormalities. ADAMTS13 activity is severely reduced. What is the immediate treatment?',o:['Platelet transfusion alone','Plasma exchange','Warfarin','Vitamin K','Splenectomy as first-line therapy'],a:1,e:'Acquired TTP is a hematologic emergency treated urgently with plasma exchange and immunomodulatory therapy.'},
{id:'M31',subject:'Medicine',q:'A patient with severe asthma has eosinophilia and markedly elevated IgE, with recurrent fleeting pulmonary infiltrates. Which diagnosis is most likely?',o:['Goodpasture syndrome','Allergic bronchopulmonary aspergillosis','Idiopathic pulmonary fibrosis','Sarcoidosis','Silicosis'],a:1,e:'ABPA occurs in asthma or cystic fibrosis and features Aspergillus sensitization, high IgE, eosinophilia and transient infiltrates/bronchiectasis.'},
{id:'M32',subject:'Medicine',q:'A patient with emphysema has an unusually low diffusing capacity for carbon monoxide. Which mechanism best explains it?',o:['Increased pulmonary capillary surface area','Destruction of alveolar-capillary surface area','Increased pulmonary blood flow','Thick mucus only','Increased hemoglobin concentration'],a:1,e:'Emphysema destroys alveolar walls and capillary beds, reducing gas exchange surface area and DLCO.'},
{id:'M33',subject:'Medicine',q:'A patient with idiopathic pulmonary arterial hypertension develops right ventricular failure. Which ventricular adaptation is initially expected?',o:['Concentric right ventricular hypertrophy','Immediate ventricular thinning','Left ventricular hypertrophy only','Reduced pulmonary vascular resistance','Atrial septal closure'],a:0,e:'Chronic pressure overload from pulmonary arterial hypertension initially produces right ventricular hypertrophy.'},
{id:'M34',subject:'Medicine',q:'A patient with sudden pleuritic chest pain, hypoxemia and tachycardia has a large pulmonary embolus. Which ECG finding is classically associated but insensitive?',o:['S1Q3T3 pattern','Diffuse ST elevation','Complete heart block','Delta waves','Electrical alternans'],a:0,e:'S1Q3T3 is a classic but neither sensitive nor specific ECG pattern of acute pulmonary embolism.'},
{id:'M35',subject:'Medicine',q:'A patient with acute kidney injury after septic shock has muddy brown granular casts. The primary lesion is:',o:['Glomerular basement membrane rupture','Acute tubular injury','Renal papillary necrosis','Interstitial fibrosis','Minimal change disease'],a:1,e:'Muddy brown granular casts are characteristic of acute tubular injury/necrosis, commonly from ischemia or nephrotoxins.'},
{id:'M36',subject:'Medicine',q:'A patient develops hematuria, hearing impairment and ocular abnormalities. Which structural protein defect is most likely?',o:['Type I collagen','Type II collagen','Type IV collagen','Elastin','Fibrillin-1'],a:2,e:'Alport syndrome results from defects in type IV collagen and can cause nephritis, sensorineural deafness and ocular abnormalities.'},
{id:'M37',subject:'Medicine',q:'A patient with severe sepsis has prolonged PT and aPTT, thrombocytopenia, low fibrinogen and elevated D-dimer. What process best explains this?',o:['Isolated immune thrombocytopenia','Disseminated intravascular coagulation','Hemophilia A','Vitamin C deficiency','TTP only'],a:1,e:'DIC causes systemic coagulation activation with consumption of platelets and coagulation factors and secondary fibrinolysis.'},
{id:'M38',subject:'Medicine',q:'A patient with iron deficiency anemia has a low MCV and increased RDW. Which laboratory pattern is expected?',o:['High ferritin and low TIBC','Low ferritin and high TIBC','High ferritin and high transferrin saturation','Normal ferritin in all cases','High serum iron'],a:1,e:'Iron deficiency typically causes low ferritin, low serum iron, high TIBC/transferrin and low transferrin saturation.'},
{id:'M39',subject:'Medicine',q:'A patient with hemolytic anemia has elevated LDH and indirect bilirubin with low haptoglobin. Which additional finding is most likely?',o:['Reticulocytopenia','Reticulocytosis','Low erythropoietin always','Low bilirubin','High haptoglobin'],a:1,e:'Hemolysis stimulates marrow compensation, producing reticulocytosis unless marrow response is impaired.'},
{id:'M40',subject:'Medicine',q:'A patient with hereditary spherocytosis develops pigment gallstones. The underlying RBC defect most commonly involves:',o:['Spectrin/ankyrin membrane cytoskeletal interactions','Beta-globin synthesis','G6PD enzyme activity','Pyruvate carboxylase','Factor VIII'],a:0,e:'Hereditary spherocytosis is commonly caused by defects in membrane proteins such as spectrin, ankyrin, band 3 or protein 4.2.'},
{id:'M41',subject:'Medicine',q:'A patient develops hemolysis after exposure to primaquine. Which enzyme deficiency predisposes to this?',o:['Pyruvate kinase','G6PD','Adenosine deaminase','Hexokinase','Glucose-6-phosphatase'],a:1,e:'G6PD deficiency reduces NADPH generation and glutathione recycling, making RBCs vulnerable to oxidative stress.'},
{id:'M42',subject:'Medicine',q:'A patient with myasthenia gravis has worsening weakness after receiving an aminoglycoside. The drug worsens weakness primarily by:',o:['Increasing acetylcholine release','Reducing neuromuscular transmission','Increasing acetylcholinesterase activity only in the brain','Blocking dopamine receptors','Increasing muscle calcium stores'],a:1,e:'Aminoglycosides can impair presynaptic acetylcholine release and worsen neuromuscular transmission in susceptible patients.'},
{id:'M43',subject:'Medicine',q:'A patient with Parkinson disease has wearing-off fluctuations on levodopa. Which mechanism best explains the complication?',o:['Permanent loss of peripheral dopamine receptors','Progressive loss of presynaptic dopaminergic buffering capacity','Increased GABA synthesis only','Excess acetylcholine breakdown','Reduced intestinal motility only'],a:1,e:'As nigrostriatal neurons are lost, the striatum loses the capacity to buffer fluctuating levodopa-derived dopamine levels.'},
{id:'M44',subject:'Medicine',q:'A patient develops acute flaccid paralysis with sensory sparing after a diarrheal illness. CSF shows albuminocytologic dissociation. Which immune target is commonly involved?',o:['Postsynaptic nicotinic receptors','Peripheral nerve gangliosides','NMDA receptors','Voltage-gated calcium channels in the CNS only','Myelin basic protein in oligodendrocytes'],a:1,e:'Guillain-Barré syndrome is associated with antibodies against peripheral nerve gangliosides in some variants, especially after Campylobacter infection.'},
{id:'M45',subject:'Medicine',q:'A patient has recurrent episodes of pancreatitis, xanthomas and very high triglycerides. Which lipoprotein is primarily elevated in familial chylomicronemia?',o:['LDL','HDL','Chylomicrons','IDL','Lp(a)'],a:2,e:'Familial chylomicronemia results from impaired lipoprotein lipase pathway activity and marked fasting chylomicron accumulation.'},
{id:'M46',subject:'Medicine',q:'A patient with severe hypertriglyceridemia is at risk of pancreatitis. Which metabolic substrate is especially abundant in the fasting plasma?',o:['Chylomicrons','HDL only','Albumin-bound bilirubin','LDL only','Ketone bodies'],a:0,e:'Marked chylomicronemia is strongly associated with pancreatitis when triglycerides are extremely elevated.'},
{id:'M47',subject:'Medicine',q:'A patient with hemochromatosis has diabetes, hepatomegaly and skin hyperpigmentation. Which laboratory finding is most characteristic?',o:['Low transferrin saturation','High transferrin saturation','Low ferritin','High ceruloplasmin','Low hepatic iron'],a:1,e:'Hereditary hemochromatosis typically produces increased transferrin saturation and ferritin with progressive tissue iron deposition.'},
{id:'M48',subject:'Medicine',q:'A patient with Wilson disease has liver disease and neurologic symptoms. Which laboratory pattern is most characteristic?',o:['High ceruloplasmin and low urinary copper','Low ceruloplasmin with increased urinary copper','High ceruloplasmin only','Low urinary copper','High ferritin as the defining test'],a:1,e:'Wilson disease commonly causes low ceruloplasmin and increased urinary copper excretion; hepatic copper is increased.'},
{id:'M49',subject:'Medicine',q:'A patient with Addison disease develops hypotension, hyperkalemia and hyperpigmentation. Which hormone pattern is expected?',o:['High cortisol, low ACTH','Low cortisol, high ACTH','High aldosterone, low renin','High cortisol, high aldosterone','Low ACTH, high aldosterone'],a:1,e:'Primary adrenal insufficiency causes low cortisol and aldosterone with compensatory high ACTH and renin.'},
{id:'M50',subject:'Medicine',q:'A patient with recurrent fasting hypoglycemia has a pancreatic beta-cell tumor. Which biochemical pattern is expected during an episode?',o:['High glucose, low insulin','Low glucose with inappropriately high insulin, C-peptide and proinsulin','Low glucose with high ketones and suppressed insulin','Low glucose with absent C-peptide','High glucose with high glucagon'],a:1,e:'Endogenous hyperinsulinism produces hypoglycemia with inappropriately elevated insulin, C-peptide and proinsulin and usually suppressed ketogenesis.'},
// PEDIATRICS
{id:'P01',subject:'Paediatrics',q:'A term neonate develops severe respiratory distress immediately after birth. Chest radiograph shows hyperinflated lungs with a mediastinal shift and bowel loops in the thorax. Which embryologic defect is most likely?',o:['Failure of pleuropericardial fusion','Posterolateral diaphragmatic defect','Esophageal atresia','Failure of midgut rotation','Tracheoesophageal fistula'],a:1,e:'A posterolateral Bochdalek diaphragmatic hernia allows abdominal viscera into the thorax and causes pulmonary hypoplasia.'},
{id:'P02',subject:'Paediatrics',q:'A neonate with severe pulmonary hypertension after meconium aspiration has right-to-left shunting through the ductus arteriosus. Which intervention directly promotes pulmonary vasodilation?',o:['Inhaled nitric oxide','Indomethacin','High-dose furosemide','Propranolol','Warfarin'],a:0,e:'Inhaled nitric oxide selectively dilates pulmonary vasculature and is used in persistent pulmonary hypertension of the newborn.'},
{id:'P03',subject:'Paediatrics',q:'A premature infant develops apnea, abdominal distension and bloody stools. Radiograph shows pneumatosis intestinalis. Which feeding-related intervention is most appropriate initially?',o:['Increase enteral feeds','Stop enteral feeds and provide supportive management','Give high-fat feeds','Start oral iron only','Perform immediate colonoscopy'],a:1,e:'Necrotizing enterocolitis requires bowel rest, decompression, antibiotics and supportive care; surgery is considered for perforation or deterioration.'},
{id:'P04',subject:'Paediatrics',q:'A 3-day-old infant has persistent vomiting, lethargy and seizures. Sodium is 124 mmol/L, potassium 6.5 mmol/L and glucose is normal. Which endocrine disorder is most concerning?',o:['Congenital hypothyroidism','Congenital adrenal hyperplasia due to 21-hydroxylase deficiency','Growth hormone deficiency','Hyperparathyroidism','Diabetes insipidus'],a:1,e:'Salt-wasting CAH causes cortisol and aldosterone deficiency with hyponatremia, hyperkalemia, dehydration and shock.'},
{id:'P05',subject:'Paediatrics',q:'A male infant has prolonged jaundice, pale stools and dark urine. Which next finding would most strongly support biliary atresia?',o:['Direct hyperbilirubinemia with absent/abnormal extrahepatic bile ducts','Indirect hyperbilirubinemia only','High unconjugated bilirubin with positive Coombs test','Normal stool color','Low GGT in every case'],a:0,e:'Biliary atresia causes conjugated hyperbilirubinemia and progressive obliteration of the extrahepatic biliary tree; prompt evaluation is essential.'},
{id:'P06',subject:'Paediatrics',q:'A 6-week-old infant has progressive projectile non-bilious vomiting and an olive-shaped mass. Which acid-base disturbance is expected?',o:['Hyperchloremic acidosis','Hypochloremic hypokalemic metabolic alkalosis','High-anion-gap acidosis','Respiratory alkalosis','Hyperkalemic acidosis'],a:1,e:'Hypertrophic pyloric stenosis causes loss of gastric HCl, producing hypochloremic, hypokalemic metabolic alkalosis.'},
{id:'P07',subject:'Paediatrics',q:'A 2-month-old has poor feeding, tachypnea and hepatomegaly. Echocardiography shows a large left-to-right ventricular septal defect. Which physical finding is most expected?',o:['Fixed split S2 only','Harsh holosystolic murmur at the lower left sternal border','Continuous machinery murmur only','Single loud S2 with no murmur','Mid-diastolic rumble only'],a:1,e:'A VSD produces a harsh holosystolic murmur, often loudest at the lower left sternal border; large defects can cause heart failure.'},
{id:'P08',subject:'Paediatrics',q:'A child with tetralogy of Fallot develops a hypercyanotic spell. Which maneuver can acutely increase systemic vascular resistance and reduce right-to-left shunting?',o:['Knee-chest positioning','Standing upright','Valsalva only','Hyperventilation with hypocapnia','Rapid fluid restriction'],a:0,e:'Knee-chest positioning increases systemic vascular resistance, reducing right-to-left shunting across the VSD and improving pulmonary blood flow.'},
{id:'P09',subject:'Paediatrics',q:'A child has recurrent respiratory infections, pancreatic insufficiency and failure to thrive. Which genetic defect is most likely?',o:['FBN1 mutation','CFTR mutation','HTT expansion','DMD deletion','RB1 mutation'],a:1,e:'Cystic fibrosis is caused by CFTR dysfunction, leading to abnormal chloride transport, viscous secretions and pancreatic insufficiency.'},
{id:'P10',subject:'Paediatrics',q:'A child with cystic fibrosis has recurrent pulmonary exacerbations. Which organism is particularly associated with chronic infection in older children?',o:['Pseudomonas aeruginosa','Streptococcus pyogenes','Clostridium tetani','Neisseria meningitidis','Helicobacter pylori'],a:0,e:'Pseudomonas aeruginosa is a major pathogen in chronic CF airway disease, especially with advancing age and structural lung damage.'},
{id:'P11',subject:'Paediatrics',q:'A 4-year-old has fever for 6 days, bilateral nonexudative conjunctivitis, strawberry tongue, cervical lymphadenopathy and hand changes. Which complication must be prevented?',o:['Rheumatic mitral stenosis','Coronary artery aneurysm','Renal cortical necrosis','Pulmonary fibrosis','Cerebral abscess'],a:1,e:'Kawasaki disease can cause coronary artery aneurysms; timely IVIG and aspirin reduce cardiovascular complications.'},
{id:'P12',subject:'Paediatrics',q:'A child has recurrent bacterial infections beginning after 6 months of age. Immunoglobulins are profoundly low and B cells are absent. Which defect is most likely?',o:['Bruton tyrosine kinase deficiency','IL-2 receptor gamma deficiency','Chronic granulomatous disease','Chediak-Higashi syndrome','MHC II deficiency'],a:0,e:'X-linked agammaglobulinemia due to BTK deficiency causes failure of B-cell maturation and very low immunoglobulins.'},
{id:'P13',subject:'Paediatrics',q:'A male infant has severe infections with bacteria, viruses and fungi. Lymphocyte studies show very low T cells and B cells with preserved NK cells. Which pattern is most consistent?',o:['X-linked SCID due to common gamma-chain defect','Adenosine deaminase deficiency','IL-7 receptor deficiency','DiGeorge syndrome','BTK deficiency'],a:1,e:'ADA deficiency causes toxic purine metabolite accumulation affecting lymphocytes and classically produces T− B− NK− SCID; a T−B−NK+ pattern points toward certain other defects.'},
{id:'P14',subject:'Paediatrics',q:'A newborn has hypocalcemic seizures, conotruncal cardiac defects and absent thymic shadow. Which chromosomal abnormality is most likely?',o:['Trisomy 21','22q11.2 deletion','45,X','47,XXY','Trisomy 18'],a:1,e:'22q11.2 deletion causes thymic hypoplasia, hypoparathyroidism and conotruncal cardiac defects.'},
{id:'P15',subject:'Paediatrics',q:'A child has recurrent catalase-positive bacterial and fungal infections and granuloma formation. Neutrophils cannot generate an oxidative burst. Which test is abnormal?',o:['Nitroblue tetrazolium/dihydrorhodamine oxidative burst testing','Direct Coombs test','Serum IgA only','Bleeding time only','Hemoglobin electrophoresis'],a:0,e:'Chronic granulomatous disease is due to NADPH oxidase dysfunction and is diagnosed by impaired oxidative burst testing.'},
{id:'P16',subject:'Paediatrics',q:'A toddler has chronic diarrhea, abdominal distension and poor weight gain after introduction of wheat. Which test is most appropriate first in an immunocompetent child?',o:['IgA anti-tissue transglutaminase with total IgA','Serum amylase','Sweat chloride','Anti-GBM antibody','Serum ceruloplasmin'],a:0,e:'Celiac disease screening begins with IgA anti-tTG and total IgA in most immunocompetent children.'},
{id:'P17',subject:'Paediatrics',q:'A 2-year-old has fever, tachypnea, crackles and lobar consolidation. Which finding would most strongly suggest bacterial rather than viral pneumonia?',o:['Diffuse wheeze only','Focal lobar consolidation with high inflammatory markers','Rhinorrhea alone','Bilateral hyperinflation only','Conjunctivitis with cough'],a:1,e:'Focal consolidation and significant systemic inflammation favor bacterial pneumonia, though clinical overlap exists.'},
{id:'P18',subject:'Paediatrics',q:'A child with nephrotic syndrome develops sudden abdominal pain and fever. Which infection is particularly associated with nephrotic syndrome due to loss of immunoglobulins and complement?',o:['Pneumococcal peritonitis','Tetanus','Rabies','Malaria only','Pertussis only'],a:0,e:'Nephrotic syndrome increases susceptibility to encapsulated bacteria, particularly Streptococcus pneumoniae, including spontaneous bacterial peritonitis.'},
{id:'P19',subject:'Paediatrics',q:'A 5-year-old has edema, heavy proteinuria and normal renal function. Biopsy is normal by light microscopy and shows diffuse foot-process effacement on electron microscopy. Which diagnosis is most likely?',o:['FSGS','Minimal change disease','Membranous nephropathy','IgA nephropathy','Post-streptococcal GN'],a:1,e:'Minimal change disease has normal LM findings and diffuse podocyte foot-process effacement on EM.'},
{id:'P20',subject:'Paediatrics',q:'A child develops cola-colored urine and edema 2 weeks after impetigo. Which complement pattern is expected?',o:['Persistently high C3','Low C3 with later normalization','Low C4 only','High C4 with low C3 permanently','Normal complement in all cases'],a:1,e:'Post-streptococcal glomerulonephritis commonly causes transient low C3 that returns toward normal over weeks.'},
{id:'P21',subject:'Paediatrics',q:'A 7-year-old has recurrent abdominal pain, palpable purpura on the legs and arthralgia. Which renal lesion may develop?',o:['IgA nephropathy','Anti-GBM disease','Minimal change disease only','Membranous nephropathy only','Amyloidosis'],a:0,e:'IgA vasculitis can cause IgA-mediated glomerulonephritis resembling IgA nephropathy.'},
{id:'P22',subject:'Paediatrics',q:'A child with severe dehydration from diarrhea is lethargic and has weak pulses. Which fluid is preferred initially for shock resuscitation?',o:['Hypotonic dextrose water','Isotonic crystalloid bolus','3% saline routinely','Albumin for every child','Oral water only'],a:1,e:'Initial pediatric shock resuscitation generally uses an isotonic crystalloid bolus with reassessment and attention to the clinical context.'},
{id:'P23',subject:'Paediatrics',q:'A child with severe acute malnutrition is hypothermic and lethargic. Which metabolic complication is particularly important to anticipate during nutritional rehabilitation?',o:['Refeeding syndrome with electrolyte shifts','Hypernatremia in every case','Hypercalcemia in every case','Thyroid storm','Polycythemia'],a:0,e:'Refeeding after severe malnutrition can cause shifts in phosphate, potassium and magnesium and may produce serious cardiopulmonary complications.'},
{id:'P24',subject:'Paediatrics',q:'A child has recurrent episodes of hypoglycemia during fasting, hepatomegaly and lactic acidosis. Which disorder is most likely?',o:['Glycogen storage disease type I','McArdle disease','Phenylketonuria','Hereditary fructose intolerance','Medium-chain acyl-CoA dehydrogenase deficiency'],a:0,e:'GSD I from glucose-6-phosphatase deficiency causes fasting hypoglycemia, hepatomegaly, lactic acidosis and hyperuricemia.'},
{id:'P25',subject:'Paediatrics',q:'An infant develops hypoketotic hypoglycemia after an overnight fast. Which disorder should be suspected?',o:['MCAD deficiency','GSD I','Hereditary spherocytosis','Congenital hypothyroidism','Galactosemia'],a:0,e:'Medium-chain acyl-CoA dehydrogenase deficiency impairs fatty-acid oxidation and causes hypoketotic hypoglycemia during fasting/illness.'},
{id:'P26',subject:'Paediatrics',q:'A newborn develops vomiting, jaundice, hepatomegaly and E. coli sepsis after milk feeds. Which metabolic disorder is most likely?',o:['Galactosemia due to GALT deficiency','PKU','MCAD deficiency','Homocystinuria','GSD V'],a:0,e:'Classic galactosemia from GALT deficiency causes liver dysfunction, jaundice, hypoglycemia and susceptibility to E. coli sepsis after lactose exposure.'},
{id:'P27',subject:'Paediatrics',q:'A newborn screening test is positive for phenylketonuria. Untreated disease is most associated with:',o:['Severe intellectual disability and seizures','Cirrhosis from infancy','Hemolysis after fava beans','Recurrent pancreatitis','Congenital nephrotic syndrome'],a:0,e:'Untreated PKU causes neurodevelopmental impairment, seizures, eczema and a characteristic musty odor; dietary treatment prevents major neurologic injury.'},
{id:'P28',subject:'Paediatrics',q:'A 6-month-old has persistent cough, recurrent infections and diffuse wheeze. Which finding would most strongly suggest an aspiration-related cause?',o:['Cough associated with feeds and recurrent focal infiltrates','Isolated eczema','Family history of asthma only','Normal feeding with no respiratory symptoms','Single episode of viral rhinitis'],a:0,e:'Temporal association with feeds and recurrent focal infiltrates strongly suggests aspiration, often from swallowing dysfunction or structural abnormalities.'},
{id:'P29',subject:'Paediatrics',q:'A child with acute severe asthma has a silent chest, exhaustion and rising PaCO2 despite oxygen and bronchodilators. This indicates:',o:['Mild disease','Impending respiratory failure','Resolution of bronchospasm','Simple anxiety','Hyperventilation syndrome'],a:1,e:'A silent chest and rising CO2 in severe asthma indicate markedly reduced airflow and respiratory muscle fatigue, requiring urgent escalation.'},
{id:'P30',subject:'Paediatrics',q:'A child has recurrent infections, chronic diarrhea and failure to thrive. Testing shows markedly reduced CD4 T cells and elevated IgM with low IgG. Which defect is most likely?',o:['CD40 ligand deficiency','BTK deficiency','C1 esterase inhibitor deficiency','NADPH oxidase deficiency','Terminal complement deficiency'],a:0,e:'X-linked hyper-IgM syndrome from CD40L deficiency impairs T-cell help for class switching, causing low IgG/IgA with normal or high IgM.'},
{id:'P31',subject:'Paediatrics',q:'A newborn with cyanosis has a single loud second heart sound and severe hypoxemia that does not improve substantially with oxygen. Which lesion is most likely?',o:['Tetralogy of Fallot','Transposition of the great arteries','Small VSD','PDA','Atrial septal defect'],a:1,e:'TGA causes parallel rather than series circulation; adequate mixing is essential and profound cyanosis occurs early.'},
{id:'P32',subject:'Paediatrics',q:'A newborn has severe cyanosis that improves with prostaglandin E1. Which lesion is especially dependent on ductal patency for systemic blood flow?',o:['Critical coarctation of the aorta','Small ASD','Uncomplicated VSD','Mild pulmonary stenosis','Partial anomalous pulmonary venous return'],a:0,e:'Critical coarctation is a ductal-dependent systemic circulation lesion; PGE1 maintains ductal patency while definitive management is arranged.'},
{id:'P33',subject:'Paediatrics',q:'A child with a new murmur has a fixed, widely split S2. Which congenital lesion is most likely?',o:['VSD','ASD','PDA','Tetralogy of Fallot','Coarctation'],a:1,e:'An atrial septal defect causes increased right-sided flow and relatively fixed splitting of S2.'},
{id:'P34',subject:'Paediatrics',q:'A child has hypertension in the upper limbs, weak femoral pulses and lower-limb claudication. Which diagnosis is most likely?',o:['Coarctation of the aorta','PDA','Pulmonary stenosis','Aortic regurgitation','VSD'],a:0,e:'Coarctation causes upper-body hypertension with reduced lower-body perfusion and delayed/weak femoral pulses.'},
{id:'P35',subject:'Paediatrics',q:'A child with sickle cell disease develops acute chest pain, fever and a new pulmonary infiltrate. Which complication is most likely?',o:['Acute chest syndrome','Nephrotic syndrome','Kawasaki disease','Croup','Pyloric stenosis'],a:0,e:'Acute chest syndrome is defined by a new pulmonary infiltrate plus respiratory symptoms/signs in a patient with sickle cell disease.'},
{id:'P36',subject:'Paediatrics',q:'A child with sickle cell disease has sudden severe anemia and reticulocytopenia after a viral prodrome. Which infection is classically implicated?',o:['Parvovirus B19','EBV','CMV','Rotavirus','RSV'],a:0,e:'Parvovirus B19 temporarily suppresses erythropoiesis and can cause an aplastic crisis in chronic hemolytic anemias.'},
{id:'P37',subject:'Paediatrics',q:'A child has bruising, bone pain, pallor and recurrent infections. CBC shows blasts and thrombocytopenia. Which test is essential to establish the diagnosis?',o:['Bone marrow examination with immunophenotyping','Sweat chloride','Echocardiography only','Urine culture only','Skin biopsy'],a:0,e:'Acute leukemia is established with bone marrow assessment and immunophenotyping to determine lineage and subtype.'},
{id:'P38',subject:'Paediatrics',q:'A child with acute lymphoblastic leukemia develops tumor lysis syndrome after chemotherapy. Which electrolyte abnormality is expected?',o:['Hypouricemia','Hyperuricemia, hyperkalemia and hyperphosphatemia with hypocalcemia','Hypokalemia and hypercalcemia','Hypernatremia only','Low phosphate with high calcium'],a:1,e:'Tumor lysis releases intracellular potassium, phosphate and nucleic acids, producing hyperkalemia, hyperphosphatemia, hypocalcemia and hyperuricemia.'},
{id:'P39',subject:'Paediatrics',q:'A child has a palpable abdominal mass that crosses the midline and is associated with elevated urinary VMA/HVA. Which tumor is most likely?',o:['Wilms tumor','Neuroblastoma','Hepatoblastoma','Rhabdomyosarcoma','Lymphoma'],a:1,e:'Neuroblastoma commonly arises from the adrenal/sympathetic chain, may cross the midline and produces catecholamine metabolites.'},
{id:'P40',subject:'Paediatrics',q:'A child has an abdominal mass arising from the kidney that typically displaces rather than encases vessels and is associated with hematuria. Which tumor is most likely?',o:['Neuroblastoma','Wilms tumor','Neurofibroma','Hepatoblastoma','Teratoma'],a:1,e:'Wilms tumor is the classic pediatric renal malignancy and can present with an abdominal mass and hematuria.'},
{id:'P41',subject:'Paediatrics',q:'A child has severe recurrent sinopulmonary infections and chronic mucocutaneous candidiasis with hypoparathyroidism. Which syndrome is most likely?',o:['DiGeorge syndrome','Autoimmune polyendocrine syndrome type 1','Wiskott-Aldrich syndrome','Bruton disease','CGD'],a:1,e:'APS-1 can include chronic mucocutaneous candidiasis, hypoparathyroidism and adrenal insufficiency due to autoimmune mechanisms.'},
{id:'P42',subject:'Paediatrics',q:'A child has fever, conjunctival injection, strawberry tongue and cervical lymphadenopathy but no rash. Which diagnosis remains most important if fever persists for 5 days?',o:['Kawasaki disease','Scarlet fever only','Measles only','Meningococcemia only','Rheumatic fever only'],a:0,e:'Incomplete Kawasaki disease can occur without all classic features; prolonged fever with compatible mucocutaneous findings warrants evaluation.'},
{id:'P43',subject:'Paediatrics',q:'A 9-month-old has recurrent episodes of cough, cyanosis and apnea during feeds. A contrast study demonstrates a tracheoesophageal fistula. Which type is most common?',o:['H-type without atresia','Esophageal atresia with distal TE fistula','Pure esophageal atresia','Proximal TE fistula with distal atresia','Double fistula with normal esophagus'],a:1,e:'The most common pattern is esophageal atresia with a distal tracheoesophageal fistula.'},
{id:'P44',subject:'Paediatrics',q:'A newborn has failure to pass meconium, abdominal distension and explosive stool after rectal examination. Which biopsy finding confirms Hirschsprung disease?',o:['Ganglion cell hyperplasia','Absence of ganglion cells in the affected segment','Villous atrophy','Crypt abscesses','Meissner plexus hypertrophy'],a:1,e:'Hirschsprung disease is caused by failure of enteric ganglion cell migration, producing an aganglionic distal bowel segment.'},
{id:'P45',subject:'Paediatrics',q:'A 5-month-old has episodic severe crying, draws up the legs and later passes currant-jelly stool. Ultrasound shows a target sign. Which diagnosis is most likely?',o:['Pyloric stenosis','Intussusception','Volvulus','Hirschsprung disease','Necrotizing enterocolitis'],a:1,e:'Intussusception produces intermittent colicky pain, vomiting and sometimes currant-jelly stool; ultrasound classically shows a target/doughnut sign.'},
{id:'P46',subject:'Paediatrics',q:'A neonate develops bilious vomiting and abdominal distension. Which diagnosis must be urgently excluded?',o:['Hypertrophic pyloric stenosis','Malrotation with midgut volvulus','Gastroesophageal reflux','Cow milk protein allergy','Functional constipation'],a:1,e:'Bilious vomiting in a neonate is an emergency until obstruction such as malrotation with volvulus is excluded.'},
{id:'P47',subject:'Paediatrics',q:'A child with congenital hypothyroidism is untreated for several months. Which neurologic consequence is the major concern?',o:['Preventable intellectual disability','Spastic paraplegia only','Isolated hearing loss only','Progressive myopia only','Cerebellar tumor'],a:0,e:'Thyroid hormone is essential for early brain development; untreated congenital hypothyroidism can cause severe irreversible neurodevelopmental impairment.'},
{id:'P48',subject:'Paediatrics',q:'A child has growth failure, delayed puberty and anosmia. Which endocrine diagnosis is most likely?',o:['Kallmann syndrome','Precocious puberty','Cushing syndrome','Congenital hyperinsulinism','Hyperparathyroidism'],a:0,e:'Kallmann syndrome is hypogonadotropic hypogonadism associated with impaired GnRH neuron migration and anosmia.'},
{id:'P49',subject:'Paediatrics',q:'A child has short stature, webbed neck, coarctation and ovarian failure. Which karyotype is most likely?',o:['45,X','47,XXY','47,XXX','46,XY','47,XY,+21'],a:0,e:'Turner syndrome is usually associated with monosomy X and features short stature, gonadal dysgenesis and congenital cardiovascular anomalies.'},
{id:'P50',subject:'Paediatrics',q:'A boy has progressive proximal muscle weakness, calf pseudohypertrophy and a positive Gowers sign. Which protein is deficient?',o:['Dystrophin','Fibrillin','Type IV collagen','Spectrin','CFTR'],a:0,e:'Duchenne muscular dystrophy results from dystrophin deficiency and is X-linked recessive.'},
{id:'P51',subject:'Paediatrics',q:'A child with Duchenne muscular dystrophy develops cardiomyopathy. Which cardiac phenotype is particularly characteristic?',o:['Dilated cardiomyopathy with myocardial fibrosis','Hypertrophic obstructive cardiomyopathy in every case','Restrictive cardiomyopathy only','Ebstein anomaly','Tetralogy of Fallot'],a:0,e:'DMD commonly causes dilated cardiomyopathy and myocardial fibrosis as disease progresses.'},
{id:'P52',subject:'Paediatrics',q:'A child has progressive ataxia, telangiectasias and recurrent sinopulmonary infections. Which laboratory abnormality is common?',o:['Elevated alpha-fetoprotein','Low ceruloplasmin','High CK only','Low bilirubin','High insulin'],a:0,e:'Ataxia-telangiectasia due to ATM dysfunction commonly features elevated alpha-fetoprotein and immunodeficiency.'},
{id:'P53',subject:'Paediatrics',q:'A child with recurrent bacterial infections has absent tonsils and very low immunoglobulins. Which cell population is most directly absent?',o:['Mature B cells','Neutrophils','NK cells only','Eosinophils','Megakaryocytes'],a:0,e:'Bruton agammaglobulinemia causes failure of B-cell maturation, resulting in absent/very low mature B cells.'},
{id:'P54',subject:'Paediatrics',q:'A child has recurrent Neisseria meningitidis infections. Which complement defect is most likely?',o:['C1 esterase inhibitor','C3 only','Terminal C5-C9 deficiency','Factor H deficiency only','Properdin excess'],a:2,e:'Terminal complement component deficiency impairs membrane attack complex formation and predisposes particularly to Neisseria infections.'},
{id:'P55',subject:'Paediatrics',q:'A child has edema, heavy proteinuria and hyperlipidemia. Which mechanism best explains the hyperlipidemia of nephrotic syndrome?',o:['Reduced hepatic lipoprotein synthesis','Increased hepatic lipoprotein synthesis in response to hypoalbuminemia plus impaired lipid catabolism','Complete absence of LDL receptors','Increased intestinal fat loss','Reduced VLDL production'],a:1,e:'The liver increases protein and lipoprotein synthesis in response to hypoalbuminemia; lipid clearance may also be reduced.'},
{id:'P56',subject:'Paediatrics',q:'A child has a harsh systolic murmur that becomes louder with standing and Valsalva. Which diagnosis is most likely?',o:['Hypertrophic obstructive cardiomyopathy','VSD','PDA','Aortic stenosis from bicuspid valve','ASD'],a:0,e:'Reduced preload intensifies dynamic LV outflow obstruction in hypertrophic obstructive cardiomyopathy.'},
{id:'P57',subject:'Paediatrics',q:'A child develops migratory polyarthritis, carditis and subcutaneous nodules several weeks after untreated pharyngitis. Which immune mechanism is central?',o:['Molecular mimicry involving streptococcal antigens','Direct bacterial invasion of the myocardium','IgE-mediated mast-cell degranulation','Immune complex disease from hepatitis B','T-cell deficiency'],a:0,e:'Acute rheumatic fever is an immune-mediated sequela of group A streptococcal pharyngitis involving molecular mimicry.'},
{id:'P58',subject:'Paediatrics',q:'A child with fever and altered consciousness has neck stiffness and a CSF profile of high neutrophils, high protein and low glucose. Which process is most likely?',o:['Bacterial meningitis','Viral meningitis','Guillain-Barré syndrome','Multiple sclerosis','Migraine'],a:0,e:'Bacterial meningitis classically produces neutrophilic pleocytosis, elevated protein and low CSF glucose.'},
{id:'P59',subject:'Paediatrics',q:'A child with meningococcal sepsis develops purpura, shock and adrenal hemorrhage. Which complication is this?',o:['Waterhouse-Friderichsen syndrome','Kawasaki syndrome','Reye syndrome','Hemolytic uremic syndrome','Goodpasture syndrome'],a:0,e:'Fulminant meningococcemia can cause DIC, shock and bilateral adrenal hemorrhage, known as Waterhouse-Friderichsen syndrome.'},
{id:'P60',subject:'Paediatrics',q:'A child develops anemia, thrombocytopenia and acute kidney injury after bloody diarrhea. Which organism is a classic cause of the underlying illness?',o:['Shiga toxin-producing E. coli','Vibrio cholerae','Clostridium botulinum','Bordetella pertussis','Mycoplasma pneumoniae'],a:0,e:'Shiga toxin-producing E. coli can cause hemorrhagic colitis followed by hemolytic uremic syndrome.'},
// EXTRA MIXED HARD QUESTIONS
{id:'X01',subject:'Integrated',q:'A patient has a high anion-gap metabolic acidosis. After calculating the delta gap, the rise in anion gap is much greater than the fall in bicarbonate. Which additional disorder is suggested?',o:['Concurrent metabolic alkalosis','Concurrent non-anion-gap metabolic acidosis','Pure respiratory acidosis','Pure respiratory alkalosis','No additional disorder'],a:0,e:'A delta gap exceeding the fall in bicarbonate suggests an additional metabolic alkalosis or chronic respiratory acidosis, depending on context.'},
{id:'X02',subject:'Integrated',q:'A patient receives a drug that blocks the Na+/K+/2Cl− cotransporter in the thick ascending limb. Which effect is expected?',o:['Increased medullary concentration gradient','Reduced calcium and magnesium reabsorption','Reduced renal blood flow as the primary action','Increased potassium reabsorption','Increased urine concentration ability'],a:1,e:'Loop diuretics inhibit NKCC2, collapsing the medullary gradient and reducing paracellular Ca2+ and Mg2+ reabsorption.'},
{id:'X03',subject:'Integrated',q:'A child with severe diarrhea receives excessive free water and develops seizures. Which brain process primarily causes the neurologic symptoms?',o:['Cellular dehydration from hypernatremia','Brain swelling from water movement into cells during acute hyponatremia','Cerebral vasoconstriction from hyperosmolarity','Reduced intracranial pressure','Myelin destruction'],a:1,e:'Acute hypotonic hyponatremia lowers plasma osmolality, causing water to enter brain cells and potentially produce cerebral edema and seizures.'},
{id:'X04',subject:'Integrated',q:'A patient has an inherited defect in LDL receptor function. Which lipoprotein concentration is expected to rise most?',o:['HDL','LDL','Chylomicrons only','Albumin','Free fatty acids only'],a:1,e:'Reduced LDL receptor-mediated clearance causes elevated circulating LDL cholesterol.'},
{id:'X05',subject:'Integrated',q:'A patient with chronic inflammation has anemia with low serum iron, low TIBC and elevated ferritin. Which mediator is central to iron sequestration?',o:['Hepcidin','Erythropoietin','Renin','Thrombopoietin','Calcitonin'],a:0,e:'Inflammation increases hepcidin, which reduces ferroportin activity and traps iron in macrophages and enterocytes.'},
{id:'X06',subject:'Integrated',q:'A child with recurrent infections has delayed umbilical cord separation and poor wound healing. Which leukocyte defect is most likely?',o:['Leukocyte adhesion deficiency','Chediak-Higashi syndrome','CGD','BTK deficiency','Terminal complement deficiency'],a:0,e:'Leukocyte adhesion deficiency causes impaired neutrophil adhesion/extravasation, delayed cord separation and recurrent bacterial infections with poor pus formation.'},
{id:'X07',subject:'Integrated',q:'A patient develops fever, rigidity and autonomic instability after receiving a dopamine antagonist. Which diagnosis is most likely?',o:['Serotonin syndrome','Neuroleptic malignant syndrome','Malignant hyperthermia','Thyroid storm','Anticholinergic toxicity'],a:1,e:'Neuroleptic malignant syndrome follows dopamine antagonism and features hyperthermia, severe rigidity, autonomic instability and elevated CK.'},
{id:'X08',subject:'Integrated',q:'A patient develops clonus, hyperreflexia, agitation and hyperthermia after serotonergic drug interaction. Which diagnosis is most likely?',o:['NMS','Serotonin syndrome','Malignant catatonia only','Opioid withdrawal','Cholinergic crisis'],a:1,e:'Serotonin syndrome is characterized by neuromuscular hyperactivity such as clonus/hyperreflexia, autonomic activation and altered mental status.'},
{id:'X09',subject:'Integrated',q:'A child has severe watery diarrhea and metabolic acidosis after a toxin activates adenylate cyclase in intestinal epithelial cells. Which intracellular messenger rises?',o:['cAMP','cGMP only','IP3 only','DAG only','Calcium only'],a:0,e:'Cholera toxin ADP-ribosylates Gs, causing persistent adenylate cyclase activation, increased cAMP and chloride/water secretion.'},
{id:'X10',subject:'Integrated',q:'A patient with a deficiency of surfactant develops diffuse atelectasis. Which cell normally produces pulmonary surfactant?',o:['Type I pneumocytes','Type II pneumocytes','Alveolar macrophages','Club cells','Ciliated columnar cells'],a:1,e:'Type II pneumocytes synthesize pulmonary surfactant, which reduces surface tension and prevents alveolar collapse.'},
];

function shuffle(arr){const a=[...arr]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a;}
function makePaper(){return shuffle(BANK).slice(0,TOTAL).map(q=>({...q, options:shuffle(q.o.map((text,i)=>({text,correct:i===q.a}))) }));}
function fmt(sec){const m=Math.floor(sec/60).toString().padStart(2,'0');const s=(sec%60).toString().padStart(2,'0');return `${m}:${s}`;}

function App(){
 const [screen,setScreen]=useState('home');
 const [name,setName]=useState('');
 const [paper,setPaper]=useState([]); const [answers,setAnswers]=useState([]); const [index,setIndex]=useState(0); const [flowIndex,setFlowIndex]=useState(0); const [skipped,setSkipped]=useState(new Set()); const [reviewedSkipped,setReviewedSkipped]=useState(new Set()); const [seconds,setSeconds]=useState(EXAM_MINUTES*60); const [startedAt,setStartedAt]=useState(null); const [history,setHistory]=useState(()=>JSON.parse(localStorage.getItem('fcpsHistory')||'[]')); const [result,setResult]=useState(null);
 useEffect(()=>{if(screen!=='exam')return; const id=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(id);finish(true,0);return 0} return s-1}),1000);return()=>clearInterval(id)},[screen]);
 const current=paper[index];
 const statuses=useMemo(()=>paper.map((_,i)=>answers[i]!=null?'answered':skipped.has(i)?'skipped':'unseen'),[paper,answers,skipped]);
 function start(){if(!name.trim())return alert('Please enter the candidate name.'); const p=makePaper();setPaper(p);setAnswers(Array(TOTAL).fill(null));setIndex(0);setFlowIndex(0);setSkipped(new Set());setReviewedSkipped(new Set());setSeconds(EXAM_MINUTES*60);setStartedAt(Date.now());setResult(null);setScreen('exam');}
 function selectOption(i){setAnswers(a=>{const n=[...a];n[index]=i;return n});setSkipped(s=>{const n=new Set(s);n.delete(index);return n});}
 function visitSkipped(i){if(skipped.has(i) && !reviewedSkipped.has(i)){setReviewedSkipped(s=>new Set(s).add(i));setIndex(i);}}
 function next(){
   if(index===TOTAL-1){finish(false);return;}
   if(index<flowIndex){setIndex(flowIndex);return;}
   if(answers[index]==null)setSkipped(s=>new Set(s).add(index));
   const nextIndex=index+1;
   setFlowIndex(nextIndex);
   setIndex(nextIndex);
 }
 function finish(auto=false, remainingSeconds=seconds){ if(!paper.length)return; const attempted=answers.filter(x=>x!=null).length; const correct=answers.reduce((sum,ans,i)=>sum+(ans!=null && paper[i].options[ans]?.correct?1:0),0); const r={name:name.trim(),date:new Date().toISOString(),correct,attempted,wrong:attempted-correct,unanswered:TOTAL-attempted,percent:Math.round(correct/TOTAL*100),duration:Math.max(0,EXAM_MINUTES*60-remainingSeconds),auto}; setResult(r);const h=[r,...history].slice(0,50);setHistory(h);localStorage.setItem('fcpsHistory',JSON.stringify(h));setScreen('result');}
 function clearHistory(){if(confirm('Delete all saved attempt history on this browser?')){setHistory([]);localStorage.removeItem('fcpsHistory')}}
 if(screen==='home') return <Home name={name} setName={setName} start={start} history={history} clearHistory={clearHistory} />;
 if(screen==='exam') return <Exam current={current} index={index} total={TOTAL} answers={answers} seconds={seconds} statuses={statuses} selectOption={selectOption} next={next} finish={()=>finish(false)} visitSkipped={visitSkipped} flowIndex={flowIndex} skipped={skipped} reviewedSkipped={reviewedSkipped}/>;
 return <Result r={result} paper={paper} answers={answers} start={start} />;
}

function Home({name,setName,start,history,clearHistory}){return <div className="shell"><header><div><div className="eyebrow">CBT SIMULATOR</div><h1>FCPS-I Medicine + Paediatrics</h1><p className="muted">High-difficulty practice • 100 SBAs • 120-minute paper</p></div><div className="badge">PRACTICE ONLY</div></header><main className="homeGrid"><section className="card hero"><h2>Simulate the computer exam</h2><p>This is designed to make a first-time computer-based candidate comfortable with the interface and time pressure.</p><ul><li>100 randomized questions selected from the built-in bank</li><li>One question visible at a time</li><li>Five single-best-answer options A–E</li><li>Previous questions are locked after moving forward</li><li>Right-side question navigator shows answered/unseen status</li><li>Finish early or let the timer auto-submit</li><li>Attempts and scores are saved on this browser by candidate name</li></ul><div className="notice"><b>Content note:</b> This is an independent practice bank, not CPSP material and not an official prediction of exam questions.</div><label>Candidate name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Dr. Ayesha Khan" onKeyDown={e=>e.key==='Enter'&&start()}/></label><button className="primary big" onClick={start}>Start 100-MCQ Mock →</button></section><section className="card"><div className="row"><h2>Previous attempts</h2><button className="linkBtn" onClick={clearHistory}>Clear</button></div>{history.length===0?<p className="muted">No attempts stored yet.</p>:<div className="history">{history.slice(0,12).map((r,i)=><div className="hist" key={i}><div><b>{r.name}</b><span>{new Date(r.date).toLocaleString()}</span></div><strong>{r.correct}/{TOTAL}<small>{r.percent}%</small></strong></div>)}</div>}<div className="mini"><b>Timing</b><span>120 minutes = 72 seconds/question.</span><span>For the real exam, follow the time/session printed on the candidate’s CPSP instructions/admit card.</span></div></section></main><footer>Educational practice tool • No patient-specific medical advice</footer></div>}

function Exam({current,index,total,answers,seconds,statuses,selectOption,next,finish,visitSkipped,flowIndex,skipped,reviewedSkipped}){return <div className="examShell"><header className="examHeader"><div><div className="eyebrow">FCPS-I CBT PRACTICE</div><b>Medicine + Paediatrics</b></div><div className={seconds<300?'timer danger':'timer'}>TIME {fmt(seconds)}</div><button className="finish" onClick={()=>{if(confirm('Finish the paper now? You will not be able to continue.'))finish()}}>Finish exam</button></header><div className="examBody"><main className="questionArea"><div className="qtop"><span>Question {index+1} of {total}</span><span>{current.subject}</span></div><h2>{current.q}</h2><div className="options">{current.options.map((op,i)=><button key={i} className={'option '+(answers[index]===i?'selected':'')} onClick={()=>selectOption(i)}><span className="letter">{LETTERS[i]}</span><span>{op.text}</span></button>)}</div><div className="nav"><span className="muted">{answers[index]==null?'Not answered':'Answer selected'}{index<flowIndex?' • Reviewing skipped question':''}</span><button className="primary" onClick={next}>{index===total-1?'Submit paper':'Next question →'}</button></div></main><aside className="side"><div className="sideTitle"><b>Questions</b><span>{answers.filter(x=>x!=null).length}/{total}</span></div><div className="legend"><span><i className="dot answered"/>Answered</span><span><i className="dot skipped"/>Skipped</span><span><i className="dot"/>Unseen</span><span><i className="dot current"/>Current</span></div><div className="grid">{statuses.map((s,i)=>{const canVisit=s==='skipped'&&!reviewedSkipped.has(i);return <button disabled={!canVisit && i!==index} className={(i===index?'current ':'')+(s==='answered'?'answered ':'')+(s==='skipped'?'skipped ':'')+(canVisit?'clickable':'')} onClick={()=>canVisit&&visitSkipped(i)} key={i}>{i+1}</button>})}</div><p className="sideNote">Skipped questions are available once for review. Reviewing one does not change your forward position; Next returns you to the question where you left off.</p></aside></div></div>}

function Result({r,paper,answers,start}){return <div className="shell"><header><div><div className="eyebrow">PAPER COMPLETE</div><h1>Performance report</h1><p className="muted">{r?.name}</p></div><div className="scoreRing"><b>{r?.percent}%</b><span>{r?.correct}/{TOTAL}</span></div></header><main className="card result"><div className="stats"><div><span>Correct</span><b>{r?.correct}</b></div><div><span>Wrong</span><b>{r?.wrong}</b></div><div><span>Unanswered</span><b>{r?.unanswered}</b></div><div><span>Time used</span><b>{fmt(r?.duration||0)}</b></div></div><h2>Question review</h2><div className="review">{paper.map((q,i)=>{const ans=answers[i];const ok=ans!=null&&q.options[ans]?.correct;return <div className={'reviewItem '+(ok?'ok':ans==null?'skip':'bad')} key={q.id}><div><b>Q{i+1}</b><span>{q.subject}</span></div><p>{q.q}</p><small>Your answer: {ans==null?'Not answered':LETTERS[ans]} • Correct: {LETTERS[q.options.findIndex(x=>x.correct)]}</small><em>{q.e}</em></div>})}</div><button className="primary big" onClick={start}>Start another randomized mock</button></main></div>}

createRoot(document.getElementById('root')).render(<App/>);
